### ISSUE TITLE
Add verification message on Rustup dependency

### ISSUE THREAD

**Issue by xstevenyung** [denoland/wasmbuild#48]
I'm new to Rust and WASM so take this as a beginner perspective.

I tried to get start on wasmbuild, but got hit with an error on trying to follow the instruction at https://deno.com/blog/wasmbuild.

It turns out homebrew doesn't install `rustup` when running `brew install rust`, instead we need to run `brew install rustup-init && rustup-init` to get the Rust tool chain.

Maybe it would be good to add a message to check if `rustup` is correctly installed for onboarding new rust dev ? or maybe just some instruction on the repo to hint to people that `rustup -V` should work instead of `cargo -V` like mentioned in the blog post ?

**Comment by dsherret** [comment]
Thanks for the feedback. I like the idea of building these instructions directly in the tool since a lot of people will be using this who are new to rust. Basically it would check for `rustup -V` and `cargo -V` then when not installed it would give an instructional error.

Also, I am updating the blog post.
