### ISSUE TITLE
Bad CPU Type on M1

### ISSUE THREAD

**Issue by kitsonk** [denoland/wasmbuild#59]
On M1 I am getting:

```
Error running wasm-opt failed. Maybe skip with --skip-opt?

Error: Bad CPU type in executable (os error 86)
```

Though it does appear that there can be ways around it: https://github.com/rustwasm/wasm-pack/issues/1098

It tried to `brew install binaryyen` but it didn't resolve the issue (as well as cargo install the `wasm-bindgen-cli`).

**Comment by tatsuya6502** [comment]
I believe the reason is that wasmbuild is downloading a wrong `wasm-opt` binary `binaryen-version_109-x86_64-macos.tar.gz` for macOS, which is built for Intel x86_64 Macs.

https://github.com/denoland/wasmbuild/blob/0.10.2/lib/wasmopt.ts#L104-L113

```typescript
const tag = "version_109";

function binaryenUrl() {
  const target = {
    "linux": "x86_64-linux",
    "darwin": "x86_64-macos",
    "windows": "x86_64-windows",
  }[Deno.build.os];
  return new URL(
    `https://github.com/WebAssembly/binaryen/releases/download/${tag}/binaryen-${tag}-${target}.tar.gz`,
  );
}
```

On Mac with Apple silicon, it should download `binaryen-version_109-arm64-macos.tar.gz` instead. https://github.com/WebAssembly/binaryen/releases/tag/version_109

So I think we need to update the above code to use `Deno.build.arch` value to get the right `target` (`arm64-macos` or `x86_64-macos`).

```console
$ deno eval "console.log(Deno.build)"
{
  target: "aarch64-apple-darwin",
  arch: "aarch64",
  os: "darwin",
  vendor: "apple",
  env: undefined
}
```

https://deno.land/api@v1.28.1?s=Deno.build
